spring:
  profiles: prod
config:
  widgetIdType: string
  repositoryType: memory
#  repositoryType: db
---
spring:
  profiles: test
config:
#  widgetIdType: string
#  repositoryType: memory
  repositoryType: db
